name: Dmesg

on: [push, pull_request]

jobs:
  other-job1:
    name: Dmesg  Job
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        printf 'PID\tOOM Score\tOOM Adj\tCommand\n'
        while read -r pid comm; do [ -f /proc/$pid/oom_score ] && [ $(cat /proc/$pid/oom_score) != 0 ] && printf '%d\t%d\t\t%d\t%s\n' "$pid" "$(cat /proc/$pid/oom_score)" "$(cat /proc/$pid/oom_score_adj)" "$comm"; done < <(ps -e -o pid= -o comm=) | sort -k 2nr
        # dmesg -w -T | egrep --line-buffered -i "oom|kill" &
        # tail /dev/zero || true
        sleep 1
        # ps -ef
        echo end
