name: Dmesg

on: [push, pull_request]

jobs:
  other-job1:
    name: Dmesg  Job
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        dmesg -w -T | egrep 'oom|kill' &
        tail /dev/zero || true
        echo end
