name: Dmesg

on: [push, pull_request]

jobs:
  other-job1:
    name: Dmesg  Job
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        dmesg -w -T | egrep -i "oom|kill" &
        #tail /dev/zero || true
        sleep 1
        ps -ef
        echo end
