name: Counting

on: [push, pull_request]

jobs:
  other-job1:
    name: Other  Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache counter
      id: cache-counter
      uses: actions/cache@v1
      with:
        path: counter
        key: README.md
    - name: Increment 
      if: steps.cache-counter.outputs.cache-hit != true
      run: |
        bash foo.sh 
    - name: Display
      run: |
        echo -n "Current count is = "
        cat counter
        echo
