name: Dmesg

on: [push, pull_request]

jobs:
  other-job1:
    name: Dmesg  Job
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        sudo dmesg -W -T &
        tail /dev/zero || true
        echo end
